default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devices_development

test:
  <<: *default
  database: devices_test

production:
  <<: *default
  database: devices_production
  username: devices
  password: <%= ENV['DEVICES_DATABASE_PASSWORD'] %>
